### PR TITLE
Fix #6: Update blackfriday import, add go.sum

### LINKED ISSUE #6: Can't build on 1.13.5 or 1.14.2
```
$ go version
go version go1.14.2 linux/amd64
$ go get github.com/emersion/matcha/cmd/matcha
# github.com/emersion/matcha
/srv/files/gopath/src/github.com/emersion/matcha/matcha.go:247:16: undefined: blackfriday.Run
/srv/files/gopath/src/github.com/emersion/matcha/matcha.go:319:16: undefined: blackfriday.Run
```

Seems like blackfriday must have changed something.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Thanks!
