### ISSUE TITLE
Can't build on 1.13.5 or 1.14.2

### ISSUE THREAD

**Issue by ghost** [emersion/matcha#6]
```
$ go version
go version go1.14.2 linux/amd64
$ go get github.com/emersion/matcha/cmd/matcha
# github.com/emersion/matcha
/srv/files/gopath/src/github.com/emersion/matcha/matcha.go:247:16: undefined: blackfriday.Run
/srv/files/gopath/src/github.com/emersion/matcha/matcha.go:319:16: undefined: blackfriday.Run
```

Seems like blackfriday must have changed something.

**Comment by emersion** [comment]
Go modules should prevent things like this. I wonder what's happening here.

Well, in any case, patches welcome.
